let mySprite = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
let Senshi = sprites.create(img`
    ....................e2e22e2e....................
    .................222eee22e2e222.................
    ..............222e22e2e22eee22e222..............
    ...........e22e22eeee2e22e2eeee22e22e...........
    ........eeee22e22e22e2e22e2e22e22e22eeee........
    .....222e22e22eeee22e2e22e2e22eeee22e22e222.....
    ...22eeee22e22e22e22eee22eee22e22e22e22eeee22...
    4cc22e22e22eeee22e22e2e22e2e22e22eeee22e22e22cc4
    6c6eee22e22e22e22e22e2e22e2e22e22e22e22e22eee6c6
    46622e22eeee22e22eeee2e22e2eeee22e22eeee22e22664
    46622e22e22e22eeee22e2e22e2e22eeee22e22e22e22664
    4cc22eeee22e22e22e22eee22eee22e22e22e22eeee22cc4
    6c622e22e22eeee22e22e2e22e2e22e22eeee22e22e226c6
    466eee22e22e22e22e22e2e22e2e22e22e22e22e22eee664
    46622e22eeee22e22e22e2e22e2e22e22e22eeee22e22664
    4cc22e22e22e22e22eeee2e22e2eeee22e22e22e22e22cc4
    6c622eeee22e22eeee22eee22eee22eeee22e22eeee226c6
    46622e22e22eeee22e22e2e22e2e22e22eeee22e22e22664
    466eee22e22e22e22e22e2e22e2e22e22e22e22e22eee664
    4cc22e22eeee22e22e22e2e22e2e22e22e22eeee22e22cc4
    6c622e22e22e22e22e22eee22eee22e22e22e22e22e226c6
    46622eeee22e22e22eeecc6666cceee22e22e22eeee22664
    46622e22e22e22eeecc6666666666cceee22e22e22e22664
    4cceee22e22eeecc66666cccccc66666cceee22e22eeecc4
    6c622e22eeecc66666cc64444446cc66666cceee22e226c6
    46622e22cc66666cc64444444444446cc66666cc22e22664
    46622cc6666ccc64444444444444444446ccc6666cc22664
    4ccc6666ccc6444bcc666666666666ccb4446ccc6666ccc4
    cccccccc6666666cb44444444444444bc6666666cccccccc
    64444444444446c444444444444444444c64444444444446
    66cb444444444cb411111111111111114bc444444444bc66
    666cccccccccccd166666666666666661dccccccccccc666
    6666444444444c116eeeeeeeeeeeeee611c4444444446666
    666e2222222e4c16e4e44e44e44e44ee61c4e2222222e666
    666eeeeeeeee4c16e4e44e44e44e44ee61c4eeeeeeeee666
    666eddddddde4c66f4e4effffffe44ee66c4eddddddde666
    666edffdffde4c66f4effffffffff4ee66c4edffdffde666
    666edccdccde4c66f4effffffffffeee66c4edccdccde666
    666eddddddde4c66f4eeeeeeeeeeeeee66c4eddddddde666
    c66edffdffde4c66e4e44e44e44e44ee66c4edffdffde66c
    c66edccdccde4c66e4e44e44e44e44ee66c4edccdccde66c
    cc66666666664c66e4e44e44e44feeee66c46666666666cc
    .c66444444444c66e4e44e44e44ffffe66c44444444466c.
    ..c64eee4eee4c66f4e44e44e44f44fe66c4eee4eee46c..
    ...c4eee4eee4c66f4e44e44e44effee66c4eee4eee4c...
    ....644444444c66f4e44e44e44e44ee66c444444446....
    .....64eee444c66f4e44e44e44e44ee66c444eee46.....
    ......6ccc666c66e4e44e44e44e44ee66c666ccc6......
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
controller.player2.moveSprite(Senshi)
forever(function () {
    if (mp.isButtonPressed(mp.playerSelector(mp.PlayerNumber.Two), mp.MultiplayerButton.Down)) {
        animation.runImageAnimation(
        Senshi,
        assets.animation`Senshi down`,
        500,
        true
        )
    } else if (mp.isButtonPressed(mp.playerSelector(mp.PlayerNumber.Two), mp.MultiplayerButton.Up)) {
        animation.runImageAnimation(
        Senshi,
        assets.animation`Senshi up`,
        500,
        true
        )
    } else if (mp.isButtonPressed(mp.playerSelector(mp.PlayerNumber.Two), mp.MultiplayerButton.Right)) {
        animation.runImageAnimation(
        Senshi,
        [img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `],
        500,
        true
        )
    } else if (mp.isButtonPressed(mp.playerSelector(mp.PlayerNumber.Two), mp.MultiplayerButton.Left)) {
        animation.runImageAnimation(
        Senshi,
        [img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `],
        500,
        true
        )
    } else {
        animation.runImageAnimation(
        Senshi,
        [img`
            ................................................
            ......................ffff......................
            ...............f..fffffcbfffff..f...............
            ..............fe.ffffbfcbfbbfff.ef..............
            ..............fefbedfcfcbfcfdebfef..............
            ..............feedeeffccbbffeeedef..............
            ..............fedeeefbcffcbfeedeef..............
            ...............fbccfbcfddfcbfccbf...............
            ...............fbcfbcfddddfcbfcbf...............
            ...............fffbcfddddddfcbfff...............
            ..............fccccf111dd111fcbbbf..............
            ...............ffffd1f1dd1f1dffff...............
            ...............fcfdd111dd111ddfbff..............
            ...............fcbfdddbddbdddfcbff..............
            ..............ffcbbcfffbbfffccbbfff.............
            .............ffffcbffffccffffbbffffff...........
            ...........fffffffcffffccffffcfffddddf.f........
            ..........fddddffcffffcffcffffcffddddf76f.......
            ..........fddddfcfccccffffccccfffd66df76f.......
            ..........fddddfcffffffffffffffcfd77676f........
            ..........fddddfcffffffffffffffcfdd777777f......
            ..........fbdddfffffffffcffffffffdddd7766f......
            ..........fddbdffffcffffcfffffffcdbbb76ff.......
            ..........fdddbcfffcffffcfffffffcbddd76f........
            ..........fdddbcfffcffffffffcffccbdbbbbbf.......
            ..........fdddbfcffcffffffffcffcfbdbdddbf.......
            ..........fdddbffcfccffffffcffcffbdbbbbbf.......
            ..........ffffffbfffcfffffccfffbfebbdddbf.......
            ..........fbbbbffbbbffffffcffbbffeebbbbbf.......
            ..........fbbbbfeffffffffffffffefeebdddbf.......
            ..........feeeefeeefbffbffffeeeeffffbbbbf.......
            ..........feeeefdeefbfbbfbbfeedf..feffff........
            ..........feeeefdeeefbbbbbfeeedf..ffeeef........
            ..........feeeeffdeeefffffeeedff..feefef........
            ..........ffffffdfdeeeeeeeeedfdf..fceef.........
            ..........fddddfddfdddddddddfddf...fffef........
            ..........fddbbfdddfffffffffdddf...feeef........
            ..........fddddffdddf.....fdddff...feeef........
            ..........fddddffdddf.....fdddff...feef.........
            ...........fffffbffff.....ffffbf...ffef.........
            ...............fbbbbf.....fbbbbf....ff..........
            ...............fbbbbf.....fbbbbf.....f..........
            ...............fbbbbf.....fbbbbf.....f..........
            ..............fdffbbf.....fbbffdf....f..........
            ..............ffddfff.....fffddff...............
            ..............fbfdfbf.....fbfdfbf...............
            ..............fddfde.......edfddf...............
            ...............feee.........eeeff...............
            `,img`
            ................................................
            ......................ffff......................
            ...............f..fffffcbfffff..f...............
            ..............fe.ffffbfcbfbbfff.ef..............
            ..............fefbedfcfcbfcfdebfef..............
            ..............feedeeffccbbffeeedef..............
            ..............fedeeefbcffcbfeedeef..............
            ...............fbccfbcfddfcbfccbf...............
            ...............fbcfbcfddddfcbfcbf...............
            ...............fffbcfddddddfcbfff...............
            ..............fccccf111dd111fcbbbf..............
            ...............ffffd1f1dd1f1dffff...............
            ...............fcfdd111dd111ddfbf...............
            ...............fcbfdddbddbdddfcbff..............
            ..............ffcbbcfffbbfffccbbff..............
            .............ffffcbffffccffffbbffffff..f........
            ...........fffffffcffffccffffcfffddddf76f.......
            ..........fddddffcffffcffcffffcffd66df76f.......
            ..........fddddfcfccccffffccccfffd77676f........
            ..........fddddfcffffffffffffffcfdd777777f......
            ..........fddddfcffffffffffffffcfdddd7766f......
            ..........fbdddfffffffffcffffffffdbbb76ff.......
            .........ffddddffffcffffcfffffffcdddd76f........
            .........fbbbbfcfffcffffcfffffffcbdbbbbbf.......
            .........fddddfcfffcffffffffcffccbdbdddbf.......
            .........fffffffcffcffffffffcffcfbdbbbbbf.......
            .........fbbbbfffcfccffffffcffcffbbbdddbf.......
            .........fbbbbffbfffcfffffccfffbfeebbbbbf.......
            .........feeeefffbbbffffffcffbbffeebdddbf.......
            .........feeeeffeffffffffffffffefeffbbbbf.......
            ........ffffffffeeefbffbffffeeeefffeffff........
            ........fdddddffdeefbfbbfbbfeedf..ffeeef........
            ........fdddbbffdeeefbbbbbfeeedf..feefef........
            ........fdddddfffdeeefffffeeedff..fceef.........
            ........fdddddffdfdeeeeeeeeedfdf...fffef........
            ........fdddddffddfdddddddddfddf...feeef........
            .........fffff.fdddfffffffffddff...feeef........
            ...............ffdddf.....fdddff...feef.........
            ...............ffdddf.....ffffbf....fef.........
            ...............fbffff.....fbbbbf....ff..........
            ...............fbbbbf.....fbbbbf.....f..........
            ...............fbbbbf.....fbbbbf.....f..........
            ...............fbbbbf.....fbbffdf....f..........
            ..............fdffbbf.....fffddff...............
            ..............ffddfff.....fbfdfbf...............
            ..............fbfdfbf......edfddf...............
            ..............fddfde........eeeff...............
            ...............feee.............................
            `,img`
            ................................................
            ......................ffff......................
            ...............f..fffffcbfffff..f...............
            ..............fe.ffffbfcbfbbfff.ef..............
            ..............fefbedfcfcbfcfdebfef..............
            ..............feedeeffccbbffeeedef..............
            ..............fedeeefbcffcbfeedeef..............
            ...............fbccfbcfddfcbfccbf...............
            ...............fbcfbcfddddfcbfcbf...............
            ...............fffbcfddddddfcbfff...............
            ..............fccccf111dd111fcbbbf..............
            ...............ffffd1f1dd1f1dffff...............
            ...............fcfdd111dd111ddfbff..............
            ...............fcbfdddbddbdddfcbff..............
            ..............ffcbbcfffbbfffccbbfff.............
            .............ffffcbffffccffffbbffffff...........
            ...........fffffffcffffccffffcfffddddf.f........
            ..........fddddffcffffcffcffffcffddddf76f.......
            ..........fddddfcfccccffffccccfffd66df76f.......
            ..........fddddfcffffffffffffffcfd77676f........
            ..........fddddfcffffffffffffffcfdd777777f......
            ..........fbdddfffffffffcffffffffdddd7766f......
            ..........fddbdffffcffffcfffffffcdbbb76ff.......
            ..........fdddbcfffcffffcfffffffcbddd76f........
            ..........fdddbcfffcffffffffcffccbdbbbbbf.......
            ..........fdddbfcffcffffffffcffcfbdbdddbf.......
            ..........fdddbffcfccffffffcffcffbdbbbbbf.......
            ..........ffffffbfffcfffffccfffbfebbdddbf.......
            ..........fbbbbffbbbffffffcffbbffeebbbbbf.......
            ..........fbbbbfeffffffffffffffefeebdddbf.......
            ..........feeeefeeefbffbffffeeeeffffbbbbf.......
            ..........feeeefdeefbfbbfbbfeedf..feffff........
            ..........feeeefdeeefbbbbbfeeedf..ffeeef........
            ..........feeeeffdeeefffffeeedff..feefef........
            ..........ffffffdfdeeeeeeeeedfdf..fceef.........
            ..........fddddfddfdddddddddfddf...fffef........
            ..........fddbbfdddfffffffffdddf...feeef........
            ..........fddddffdddf.....fdddff...feeef........
            ..........fddddffdddf.....fdddff...feef.........
            ...........fffffbffff.....ffffbf...ffef.........
            ...............fbbbbf.....fbbbbf....ff..........
            ...............fbbbbf.....fbbbbf.....f..........
            ...............fbbbbf.....fbbbbf.....f..........
            ..............fdffbbf.....fbbffdf....f..........
            ..............ffddfff.....fffddff...............
            ..............fbfdfbf.....fbfdfbf...............
            ..............fddfde.......edfddf...............
            ...............feee.........eeeff...............
            `,img`
            ................................................
            ................................................
            ......................ffff......................
            ...............f..fffffcbfffff..f...............
            ..............fe.ffffbfcbfbbfff.ef..............
            ..............fefbedfcfcbfcfdebfef..............
            ..............feedeeffccbbffeeedef..............
            ..............fedeeefbcffcbfeedeef..............
            ...............fbccfbcfddfcbfccbf...............
            ...............fbcfbcfddddfcbfcbf...............
            ...............fffbcfddddddfcbffff..............
            ..............fccccf111dd111fcbbb...............
            ...............ffffd1f1dd1f1dffff...............
            ...............fcfdd111dd111ddfbff..............
            ...............fcbfdddbddbdddfcbff..............
            ..............ffcbbcfffbbfffccbbfff.............
            ..............fffcbffffccffffbbffffff...........
            .............fffffcffffccffffcfffddddf..........
            ...........ffffffcffffcffcffffcffddddf.f........
            ..........fddddfcfccccffffccccfffddddf76f.......
            ..........fddddfcffffffffffffffcfd66df76f.......
            ..........fddddfffffffffcffffffffd77676f........
            ..........fddddffffcffffcfffffffcdd777777f......
            ..........fbdddcfffcffffcfffffffcdddd7766f......
            .........ffddddcfffcffffffffcffccdbbb76ff.......
            .........fbbbbffcffcffffffffcffcfbddd76f........
            .........fddddfffcfccffffffcffcffbdbbbbbf.......
            .........fffffffbfffcfffffccfffbfbdbdddbf.......
            .........ffffffffbbbffffffcffbbffbdbbbbbf.......
            .........fdddddfeffffffffffffffefebbdddbf.......
            .........fdddbbfeeefbffbffffeeeefeebbbbbf.......
            .........fdddddfdeefbfbbfbbfeedf.eebdddbf.......
            .........fdddddfdeeefbbbbbfeeedf.fffbbbbf.......
            .........fdddddffdeeefffffeeedff..feffff........
            ..........ffffffdfdeeeeeeeeedfdf..ffeeef........
            ...............fddfdddddddddfddf..feefef........
            ...............fdddfffffffffdddf..fceef.........
            ...............ffdddf.....fdddff...fffef........
            ...............fbffff.....fdddff...feeef........
            ...............fbbbbf.....ffffbf...feeef........
            ...............fbbbbf.....fbbbbf...feef.........
            ...............fbbbbf.....fbbbbf...ffef.........
            ..............fdffbbf.....fbbbbf....ff..........
            ..............ffddfff.....fbbffdf....f..........
            ..............fbfdfbf.....fffddff....f..........
            ..............fddfde......fbfdfbf....f..........
            ...............feee........edfddf...............
            ............................eeeff...............
            `],
        500,
        true
        )
    }
})
